version: "3.3"

services:
  app:
    image: drf-flat
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      DB_NAME: drf_flat
      DB_USER: flat
      DB_PASSWORD: flatpassword
      DB_HOST: database

  database:
    image: postgres:13.3
    volumes:
      - db-drf-flat:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: flat
      POSTGRES_PASSWORD: flatpassword
      POSTGRES_DB: drf_flat

volumes:
  db-drf-flat: